# Generated by Django 5.1.15 on 2026-09-26 16:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "numero",
                    models.PositiveIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                ("valida_hasta", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviada", "Enviada al cliente"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                            ("facturada", "Facturada"),
                            ("vencida", "Vencida"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("enviada_en", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotizaciones",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "cotización",
                "verbose_name_plural": "cotizaciones",
                "ordering": ["-fecha", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoTributario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "tipo_dte",
                    models.IntegerField(
                        choices=[
                            (33, "Factura electrónica (afecta)"),
                            (34, "Factura electrónica exenta"),
                            (39, "Boleta electrónica"),
                            (41, "Boleta electrónica exenta"),
                            (52, "Guía de despacho"),
                            (56, "Nota de débito"),
                            (61, "Nota de crédito"),
                        ],
                        default=33,
                    ),
                ),
                ("folio", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fecha_emision",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "monto_neto",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "monto_exento",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "iva",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "estado_sii",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de envío"),
                            ("enviado", "Enviado al SII"),
                            ("aceptado", "Aceptado"),
                            ("aceptado_reparos", "Aceptado con reparos"),
                            ("rechazado", "Rechazado"),
                            ("anulado", "Anulado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("track_id", models.CharField(blank=True, max_length=60)),
                ("emisor_backend", models.CharField(blank=True, max_length=40)),
                ("error_mensaje", models.TextField(blank=True)),
                ("xml", models.FileField(blank=True, null=True, upload_to="dte/xml/")),
                ("pdf", models.FileField(blank=True, null=True, upload_to="dte/pdf/")),
                ("enviado_al_cliente_en", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos",
                        to="ventas.cotizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento tributario",
                "verbose_name_plural": "documentos tributarios",
                "ordering": ["-fecha_emision", "-folio"],
            },
        ),
        migrations.CreateModel(
            name="ItemCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=2, default=1, max_digits=12),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("exento", models.BooleanField(default=False)),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ventas.cotizacion",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogo.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "ítem de cotización",
                "verbose_name_plural": "ítems de cotización",
            },
        ),
    ]
