# Generated by Django 5.1.15 on 2026-10-03 13:03

import uuid
from django.db import migrations, models


def asignar_claves(apps, schema_editor):
    # Una clave distinta por documento existente (un default en AddField
    # daría la misma a todos y fallaría la restricción unique).
    Documento = apps.get_model("ventas", "DocumentoTributario")
    for doc in Documento.objects.all():
        doc.clave_idempotencia = uuid.uuid4()
        doc.save(update_fields=["clave_idempotencia"])


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentotributario',
            name='advertencias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentotributario',
            name='clave_idempotencia',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(asignar_claves, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='documentotributario',
            name='clave_idempotencia',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documentotributario',
            name='track_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
