# Generated by Django 5.1.15 on 2026-10-03 13:03

import core.validators
import facturacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaEmisora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(help_text='Ej: 76192083-9', max_length=12, validators=[core.validators.validar_rut], verbose_name='RUT')),
                ('razon_social', models.CharField(help_text='Tal como aparece en el SII.', max_length=100, verbose_name='Razón social')),
                ('giro', models.CharField(max_length=80, verbose_name='Giro')),
                ('actividades', models.CharField(help_text='Código(s) de 6 dígitos del SII, separados por coma. Máximo 4.', max_length=30, validators=[facturacion.models.validar_actividades], verbose_name='Códigos de actividad económica')),
                ('direccion', models.CharField(max_length=70, verbose_name='Dirección')),
                ('comuna', models.CharField(max_length=20, verbose_name='Comuna')),
                ('ciudad', models.CharField(blank=True, max_length=20, verbose_name='Ciudad')),
                ('codigo_sucursal', models.CharField(blank=True, help_text='Código de la dirección desde donde se factura (Mi SII > Direcciones). Ej: 88482059.', max_length=10, verbose_name='Código de sucursal SII')),
                ('correo', models.EmailField(blank=True, max_length=80, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'empresa emisora',
                'verbose_name_plural': 'empresa emisora',
            },
        ),
    ]
