# Generated by Django 5.1.15 on 2026-10-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaemisora',
            name='logo',
            field=models.ImageField(blank=True, upload_to='empresa/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='empresaemisora',
            name='nombre_fantasia',
            field=models.CharField(blank=True, help_text='Nombre comercial que se muestra en la app y en las cotizaciones (ej: Alto Nivel).', max_length=80, verbose_name='Nombre de fantasía'),
        ),
        migrations.AddField(
            model_name='empresaemisora',
            name='sitio_web',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sitio web'),
        ),
    ]
