# Generated by Django 5.1.15 on 2026-09-26 16:26

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "rut",
                    models.CharField(
                        help_text="Ej: 76192083-9",
                        max_length=12,
                        unique=True,
                        validators=[core.validators.validar_rut],
                        verbose_name="RUT",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=200, verbose_name="Razón social"),
                ),
                (
                    "giro",
                    models.CharField(blank=True, max_length=200, verbose_name="Giro"),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Dirección"
                    ),
                ),
                (
                    "comuna",
                    models.CharField(blank=True, max_length=100, verbose_name="Comuna"),
                ),
                (
                    "ciudad",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "correo",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Teléfono"
                    ),
                ),
                (
                    "contacto",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Nombre de contacto"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
                "ordering": ["razon_social"],
            },
        ),
    ]
